### ISSUE TITLE
Temporary no-login view

### ISSUE THREAD

**Issue by turian** [turian/audio-discrimination-crowdsource#104]
Since google auth doesn't really work yet, but we want to try the task workflow, can I suggest we have a temporary view?

/login_without_password?email=turian@blahblahblah

And if you go there, it auths you as that user?

(And creates an annotator row for you if that email doesn't exist)

**Comment by DeFidelity** [comment]
I suggest we create the traditional login with email/username and password instead. Or what do you think?

**Comment by turian** [comment]
@DeFidelity Nah too much work getting email delivered correctly. Let's do this please

**Comment by DeFidelity** [comment]
Okay, we'll go on with it the way you described then.
