### ISSUE TITLE
Experiment type details.

### ISSUE THREAD

**Issue by DeFidelity** [turian/audio-discrimination-crowdsource#123]
Primarily, there are only two experiment types and they are A/B experiment type or 2AFC experiment type.

## A/B experiment type
A/B test (experiment type) is A or B is better. I might have a "add salt" experiment and then I give  annotators dishes A and B but I don't tell them one has more salt and I see which they like better. That's an A/B test.

## 2AFC experiment type
2AFC test is I give you four dishes. Three don't have salt (A) and one has salt (B). I give you them like this "AAB", "ABA", "BBA", "BAB". I don't explain to you that I'm adding salt. I am experimenting to see how much salt you can detect. Maybe under 1g of salt you cannot taste anymore. You answer "XXY",, which means that you think the first and second dish are the same and the third is different, or you answer  "XYX" which means that you think the first and third dish are the same and the second one is different.

Thus an A/B test is for determining what people prefer and 2AFC test is for determining what people can sense or perceive.

However, once you decide to do A/B test in order to create the tastiest dish, you might have "salt experiment", "sugar experiment" e.t.c. The same thing applies to 2AFC when determining people's sensitivity.

**Comment by turian** [comment]
Should be a PR for the README. And maybe give examples how this ties into ExperimentTypeTaskPresentation and ExperimentTypeAnnotation
