### ISSUE TITLE
Confusing README

### ISSUE THREAD

**Issue by turian** [turian/audio-discrimination-crowdsource#16]
```
- Copy `fixtures/allauth.json.tmpl` to `fixtures/allauth.json`
- In `fixtures/allauth.json` for `DEVELOPMENT_MODE = True` if not using `127.0.0.1:8000` then replace `127.0.0.1:8000` with your domain.
```

But the file has:

```
[
    {
        "model":"sites.site",
        "pk":1,
        "fields":{
            "domain":"audiodiscrimination.com",
            "name":"audiodiscrimination.com"
        }
    },
    {
        "model":"sites.site",
        "pk":2,
        "fields":{
            "domain":"127.0.0.1:8000",
            "name":"127.0.0.1:8000"
        }
    }
]
```

Do you mean delete one?

**Comment by Programmer-yar** [comment]
No, I mean replace the `127.0.0.1:8000` with staging domain if you are using `DEVELOPMENT_MODE=True` and not using `localhost:8000`

**Comment by turian** [comment]
I don't get it.

Please show me three versions of `fixtures/allauth.json`:

1) for localhost
2) for staging
3) for prod

So I can understand

**Comment by Programmer-yar** [comment]
For localhost & production:
```
[
    {
        "model":"sites.site",
        "pk":1,
        "fields":{
            "domain":"audiodiscrimination.com",
            "name":"audiodiscrimination.com"
        }
    },
    {
        "model":"sites.site",
        "pk":2,
        "fields":{
            "domain":"127.0.0.1:8000",
            "name":"127.0.0.1:8000"
        }
    }
]
```
For staging when `DEVELOPMENT_MODE=True`:
```
[
    {
        "model":"sites.site",
        "pk":1,
        "fields":{
            "domain":"audiodiscrimination.com",
            "name":"audiodiscrimination.com"
        }
    },
    {
        "model":"sites.site",
        "pk":2,
        "fields":{
            "domain":"staging.audiodiscrimination.com",
            "name":"staging.audiodiscrimination.com"
        }
    }
]
```

**Comment by Programmer-yar** [comment]
Ok, I can simplify this further, I will submit the changes in PR

**Comment by Programmer-yar** [comment]
The `pk` (primary key) in above JSON is used by google Oauth to check which site to use. 
You can see that in `settings.py` file and this part
```
SITE_ID = 1
if DEVELOPMENT_MODE:
    SITE_ID = 2
```
so, when In development the `pk=2` will be used while without development mode `pk=1`

**Comment by Programmer-yar** [comment]
I plan to simplify this by keeping only One JSON object like this:
```
[
    {
        "model":"sites.site",
        "pk":1,
        "fields":{
            "domain":"127.0.0.1:8000",
            "name":"127.0.0.1:8000"
        }
    }
]
```
You can create a copy of fixture, add your site name and then load fixture.
I can update the settings and README.md for this
Let me know of your thoughts

**Comment by turian** [comment]
I mean maybe the simplest thing is have all THREE in one JSON. Then you don't need to edit it manually.

And then the code is smart enough to figure out if you are local, staging, or prod. That would be most automatic and easiest for maintainers.

**Comment by Programmer-yar** [comment]
> I mean maybe the simplest thing is have all THREE in one JSON. Then you don't need to edit it manually.
> 
> And then the code is smart enough to figure out if you are local, staging, or prod. That would be most automatic and easiest for maintainers.

Let me think about it

**Comment by turian** [comment]
The best is if there is NO manual intervention needed by the admin during installation.

**Comment by Programmer-yar** [comment]
OK

**Comment by Programmer-yar** [comment]
I have tried some settings. I think it will be better if we use three options in `DEVELOPMENT_MODE` environment variable.
The three options can be:
- `production` for Production site
- `stage` for stagin site
- `local` for localhost

In this way, we can select the site in settings and load all three sites from fixtures without any change

**Comment by turian** [comment]
Okay. Sounds good. Please document it carefully. Hopefully it makes the README much simpler too

**Comment by turian** [comment]
@Programmer-yar This is not done. The README still makes you jump around and copy a tmpl file. Why?
