### ISSUE TITLE
Why do we ever need a signup page?

### ISSUE THREAD

**Issue by turian** [turian/audio-discrimination-crowdsource#17]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/65918/189672692-298302ac-3361-4ae0-8d97-5aba32facab5.png">

If you already have completed Google OAuth, you don't need to choose a username or an email address. We should just make their email address their username automatically and skip this page.

**Comment by Programmer-yar** [comment]
Yes you are right, I will remove the signup page
