### ISSUE TITLE
Dedicated API for admin

### ISSUE THREAD

**Issue by Programmer-yar** [turian/audio-discrimination-crowdsource#29]
Create an API endpoint which can be accessed by admin only. Initially this API should return `hello`. Avoid using JWT authentication.
Take guidance from [this](https://www.guguweb.com/2022/01/23/django-rest-framework-authentication-the-easy-way/) link 
Some settings to expect:
- url `polls/api/v1/admin-api/`
- request method allowed `GET`
- Pass auth `Token` in request header
- view is called `AdminAPIView`
- The `AdminAPIView` will inherit from Django Rest Framework (DRF) `APIView`
- The `AdminAPIView` will use following authentication classes from DRF:
  - `SessionAuthentication`, `BasicAuthentication`
- The `AdminAPIView` will use following permission classes:
  - `permissions.IsAuthenticated` (from DRF), `IsAdmin` (custom permission class to check whether the user is admin)
- The endpoint will return JSON response of `{"data": "hello"}` initially and status code of `200` for successful requests

**Comment by turian** [comment]
Like in your proposal, how do you get the key/token/cookie whatever for the admin?

Can you explain?

Like I understand the idea that a logged in admin can go to a page that gives them a token, and then they can use the token in the HTTP API request. But I don't understand how it works in your proposal. Could you explain?

**Comment by Programmer-yar** [comment]
> 

Yes, mostly the token authentication is used with API.
Can I know which platform you will be using to make API call?

**Comment by Programmer-yar** [comment]
> Sure, this looks great. Let's do it.
> 
> Another approach we might consider, rather than using cookies, is just to issue users (in this case ONLY the admin for now) a token. I guess many APIs use tokens not cookies. Here's an example: https://simpleisbetterthancomplex.com/tutorial/2018/11/22/how-to-implement-token-authentication-using-django-rest-framework.html
> 
> He also links to a simple codebase
> 
> Does this seem more mature (in terms of the new requirements like djangorestframework being actively maintained)?
> 
> (Part of me is beginning to think we should have used auth0 for social login and API protection, but I think we've already bit the bullet on doing google-oauth ourselves so migrating might just be a waste of time: https://auth0.com/docs/quickstart/backend/django/01-authorization)


Yes, mostly the token authentication is used with API.
Can I know which platform you will be using to make API call?

**Comment by Programmer-yar** [comment]
> Like in your proposal, how do you get the key/token/cookie whatever for the admin?
> 
> Can you explain?
> 
> Like I understand the idea that a logged in admin can go to a page that gives them a token, and then they can use the token in the HTTP API request. But I don't understand how it works in your proposal. Could you explain?

Yes, it will be session cookie based authentication which is included in django, Django Rest Framework (DRF) will also use that when we specify `SessionAuthentication` in `permission_classes`
The `session` cookie contains session Id while the data corresponding to that session is stored on server side.

https://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication
https://docs.djangoproject.com/en/4.1/topics/http/sessions/

**Comment by turian** [comment]
> Can I know which platform you will be using to make API call?

I don't know. `curl` to test it but then probably Python `requests` library for my data analysis.

**Comment by turian** [comment]
> Yes, it will be session cookie based authentication which is included in django, Django Rest Framework (DRF) will also use that when we specify `SessionAuthentication` in `permission_classes`
> The `session` cookie contains session Id while the data corresponding to that session is stored on server side.

You still haven't answered my question.

If the workflow you're proposing this:
1) Admin logs on to the website.
2) Admin gets a session cookie, maybe it's a view in the admin page: "Here is your session cookie".
3) Admin copy and pastes that session cookie as an environment variable.
4) Admin runs a python script using requests and the cookie environment variable as one of the parameters posted to the API.
5) Some time later the cookie expires and the admin has to log into the site and get a new cookie.

Is that correct? Or correct me what I'm missing.

If so, why not do API tokens (like most web services) which is something like this:
1) Admin logs on to the website.
2) Admin goes to the API token page, it's a view in the admin page: "Here is your API token." (The API token is a randomly generated long string.)
3) Admin copy and pastes that API token as an environment variable.
4) Admin runs a python script using requests and the API token environment variable as one of the parameters posted to the API.

That seems simpler. Because it doesn't involve cookie expiration. Additionally, it seems more secure because the cookie grants you full admin privileges. The API token only allows fewer database interactions. And security aside, the API token doesn't require that you keep logging in, particularly if the batch job takes a while and your cookie expires in the middle of it.

**Comment by turian** [comment]
https://stackoverflow.blog/2021/10/06/best-practices-for-authentication-and-authorization-for-rest-apis/

```
When a user signs up for access to your API, generate an API key:

var token = crypto.randomBytes(32).toString('hex');
Store this in your database, associated with your user.
Carefully share this with your user, making sure to keep it as hidden as possible. You might want to show it only once before regenerating it, for instance.
Have your users provide their API keys as a header, like

curl -H "Authorization: apikey MY_APP_API_KEY" https://myapp.example.com
To authenticate a user’s API request, look up their API key in the database.
When a user generates an API key, let them give that key a label or name for their own records. Make it possible to later delete or regenerate those keys, so your user can recover from compromised credentials.
```

**Comment by Programmer-yar** [comment]
> > Yes, it will be session cookie based authentication which is included in django, Django Rest Framework (DRF) will also use that when we specify `SessionAuthentication` in `permission_classes`
> > The `session` cookie contains session Id while the data corresponding to that session is stored on server side.
> 
> You still haven't answered my question.
> 
> If the workflow you're proposing this:
> 
>     1. Admin logs on to the website.
> 
>     2. Admin gets a session cookie, maybe it's a view in the admin page: "Here is your session cookie".
> 
>     3. Admin copy and pastes that session cookie as an environment variable.
> 
>     4. Admin runs a python script using requests and the cookie environment variable as one of the parameters posted to the API.
> 
>     5. Some time later the cookie expires and the admin has to log into the site and get a new cookie.
> 
> 
> Is that correct? Or correct me what I'm missing.
> 
> If so, why not do API tokens (like most web services) which is something like this:
> 
>     1. Admin logs on to the website.
> 
>     2. Admin goes to the API token page, it's a view in the admin page: "Here is your API token." (The API token is a randomly generated long string.)
> 
>     3. Admin copy and pastes that API token as an environment variable.
> 
>     4. Admin runs a python script using requests and the API token environment variable as one of the parameters posted to the API.
> 
> 
> That seems simpler. Because it doesn't involve cookie expiration. Additionally, it seems more secure because the cookie grants you full admin privileges. The API token only allows fewer database interactions. And security aside, the API token doesn't require that you keep logging in, particularly if the batch job takes a while and your cookie expires in the middle of it.

I got your question now.
As you have mentioned you may be using `requests`
The workflow that I proposed:
1- User passes in their credentials to the login API
2- If credentials are matched in the database then a `session` object is created on server side and a cookie called `sessionid` is returned.
3- In case you are using `requests`, you can access that `sessionid` using `response.cookies['sessionid']`
4- you can add that cookie to `Request` header for continued authorized requests

For token based authentication:
- Everything same as above but the token is generated which is encryption of user creds
- The token needs to be passed in headers for authorized requests

**Comment by Programmer-yar** [comment]
With token based system we can also generate and show tokens to user on app page, from where they can copy that and can use in request headers

**Comment by turian** [comment]
@Programmer-yar Please do this.
