### ISSUE TITLE
Create tasks batch job

### ISSUE THREAD

**Issue by Programmer-yar** [turian/audio-discrimination-crowdsource#31]
Depends on #29 
One Batch row and many Task rows (with
this Batch) are written to the database. Either
`CurrentBatch.current_batch_gold` or `CurrentBatch.current_batch_eval`
with this Batch are written to the database.

**Comment by turian** [comment]
This is not at all ready.

**Comment by Programmer-yar** [comment]
Some settings to expect in this endpoint:
- url `/api/v1/batch-task/`
- request method allowed `POST` (as we only want to create Batch and related tasks)
- view can be called `BatchTaskAPIView`
- The `BatchTaskAPIView` will inherit from Django Rest Framework (DRF) `APIView`
- I plan to create 2 serializers: `BatchSerializer` for `Batch` model and `TaskSerializer` for Task model
- The `BatchTaskAPIView` will use following authentication classes from DRF:
  - `SessionAuthentication`, `BasicAuthentication` (will be used temporarily)
- The `BatchTaskAPIView` will use following permission classes:
  - `permissions.IsAuthenticated` (from DRF), `IsAdmin` (custom permission class to check whether the user is admin)
- The endpoint will return JSON response of `{"status": "success"}` and status code of `201` (created)

**Comment by turian** [comment]
1) What are the serializers?
2) Why use session authentication instead of keys?

More importantly, you are missing the most basic and crucial steps in the API.

**WHAT ARE THE ARGUMENTS PASSED IN AND WHAT ARE THEIR TYPES?**

**WHAT ARE THE PRECONDITIONS THAT MUST BE CHECKED ON THE ARGUMENTS?**

**WHAT ARE THE POSTCONDITIONS THAT MUST HOLD**

i.e. what is the contract of this API method?

**Comment by Programmer-yar** [comment]
1. Serializers convert database objects to JSON and JSON to database objects (specifically in case of django).
2. I will favour token based authentication (if you are the only one using the endpoints I don't think it will matter)

**Comment by Programmer-yar** [comment]
- I need to finalize the arguments and their types ( I will share them here soon)
- Data validation is checked by serializer's `is_valid` method
- Post condition in this case to check will only be status code which should be 201

**Comment by DeFidelity** [comment]
Task completed according to spec
