### ISSUE TITLE
The link for admin-api breaks due to a typo in url naming. Will be fixing that.

### ISSUE THREAD

**Issue by najamF18** [turian/audio-discrimination-crowdsource#78]
![image](https://user-images.githubusercontent.com/78504213/220168976-aadeac59-0748-456c-ab4b-2b7abc481113.png)

**Comment by DeFidelity** [comment]
Is this fixed now?

**Comment by DeFidelity** [comment]
I just reviewed and approved the pr, kindly check the pr I tagged you on.
