### ISSUE TITLE
If there are no instances CurrentBatchEval or CurrentBatchGold in db the code will break

### ISSUE THREAD

**Issue by najamF18** [turian/audio-discrimination-crowdsource#80]

**Comment by DeFidelity** [comment]
This issue can be closed if you've added and committed an error handling code to resolve this.

**Comment by najamF18** [comment]
> This issue can be closed if you've added and committed an error handling code to resolve this.

Yes I have added the code for error handling. Will close it. Thanks for your feedback

**Comment by najamF18** [comment]
The code to handle this error has been added.
