### ISSUE TITLE
fly.io asking for credit card

### ISSUE THREAD

**Issue by haradhansharma** [turian/audio-discrimination-crowdsource#86]
Error unknown command "iad" for "flyctl launch"
Error unknown command "mad" for "flyctl launch"
Error We need your payment information to continue! Add a credit card or buy credit: https://fly.io/dashboard/haradhan-sharma-310/billing

I have no Apps created yet. Just trying to follow the doc

**Comment by DeFidelity** [comment]
You'll need a credit card before you can proceed, however you'll not be debited, unless you have more than 3apps running.
So, stick to deploying "staging" only.
