### ISSUE TITLE
Admin dashboard

### ISSUE THREAD

**Issue by DeFidelity** [turian/audio-discrimination-crowdsource#89]
Depend on: https://github.com/turian/audio-discrimination-crowdsource/blob/main/README-spec.md#admin-dashboard

Description:
Add an Admin Dashboard view to the project. The dashboard should contain a list of experiments. 
-  View  name: `AdminDashboardView` that inherits the base view class from `django.views.View`
-  Request Methods: Get
-  Permission: Allow admin users only.
-  Content: All experiment lists.
-  A button that shows all available data in the database.
When an admin user clicks on an experiment from the list, they should be redirected to the Admin Experiment View. The Admin Experiment View should have a link to the Admin User View. Additionally, there should be a simple link or button that allows an admin user to view all raw tables. This functionality should be the default Django admin functionality.

**Comment by turian** [comment]
Approved. Easy

**Comment by najamF18** [comment]
> @najamF18 kindly work on this.

Sure.

**Comment by najamF18** [comment]
> > @najamF18 kindly work on this.
> 
> Sure.

Hi @DeFidelity for this task we will need to add another model by the name "experiment" right? and it will have two fields "name" and "type". Please let me know if I am correct

**Comment by DeFidelity** [comment]
@najamF18, you might need to check this: https://github.com/turian/audio-discrimination-crowdsource/blob/main/README-spec.md#experiment-types to fully understand you'll need to read it through the User Task Work Flow heading, experiment is literally tasks but please read that

**Comment by DeFidelity** [comment]
@najamF18, reading through the model tab now, and I found that you'll be creating three new tables in db for experiments, check here: https://github.com/turian/audio-discrimination-crowdsource/blob/main/README-spec.md#models

**Comment by najamF18** [comment]
> @najamF18, reading through the model tab in the spec readme now, I found that you'll be creating three new tables in db for experiments, check here: https://github.com/turian/audio-discrimination-crowdsource/blob/main/README-spec.md#models

I guess its four. *Experiment*, *Experiment Type*, *Experiment Annotation* and *Experiment Presentation*. Please correct me if I am wrong

**Comment by turian** [comment]
Yeah you need four

**Comment by najamF18** [comment]
> Yeah you need four

task_presentation: string For 2AFC: "AAB", "ABA", "BBA", "BAB". For A/B: "AB", "BA". We will have to implement ajax request to implement this feature. When the user will select "2AFC"  we wll show "AAB", "ABA", "BBA", "BAB" and vice versa.

**Comment by najamF18** [comment]
> > Yeah you need four
> 
> task_presentation: string For 2AFC: "AAB", "ABA", "BBA", "BAB". For A/B: "AB", "BA". We will have to implement ajax request to implement this feature. When the user will select "2AFC" we wll show "AAB", "ABA", "BBA", "BAB" and vice versa.

In the future if we will be implementing a View where users can create experiments, we may need to add ajax to achieve this feature. Please let me know your thoughts on it.

**Comment by turian** [comment]
@najamF18 we are using HTMX. No javascript no AJAX.

Also, I don't know if this needs to be dynamic. Django can render the view as HTML when showing tasks to the User.

**Comment by DeFidelity** [comment]
Yes @najamF18, we would be using HTMX to trigger ajax request, it's fairly straightforward to start with just add attributes to your html it's done.
