### ISSUE TITLE
Admin User View

### ISSUE THREAD

**Issue by DeFidelity** [turian/audio-discrimination-crowdsource#90]
Depends on: https://github.com/turian/audio-discrimination-crowdsource/blob/main/README-spec.md#admin-dashboard

This would be reached through a button/tab in the admin panel named `manage annotators on click admin user should be redirected to `AdminManagementView`

### AdminManagementView GET method
Func:
- View name: `AdminManagementView` that inherits from View from `django.views.View`
-  Permission: Only admin users have access to the page
-  On get method:
    - Issue a list of annotators in an HTML table
        - A column to input annotators' hourly rate as float
        - Other column includes:
            - email 
            - experiment name 
            - number of tasks completed 
            - percent of gold correct 
            - interannotator agreement 
            - ROI 
            - lock 
            - delete
        - Locked annotators have a grey background to signify that they are locked.

For all these attributes to be associated, we would need a profile page through a database table named `AnnotatorProfile` for annotators and we can add all these attributes as part of their profile column, which is good cause that is the only way for them to get informations about their journey on the platform.
This user profile table would have a link to the base `User` table and the fields would be an extension to items in the user table but only for the annotator users.

### AdminManagementView POST method 
All write jobs would be triggered in the HTML through HTMX for dynamic rendering and spa feel (no full page refresh).

There might not be any need for a post method for now, considering the fact that we have other views managing the two [Batch Admin Jobs](https://github.com/turian/audio-discrimination-crowdsource/blob/main/README-spec.md#batch-admin-jobs) which would be triggered with htmx when required.

There might also be a need for a mixin here, in case the admin selects locked users and normal users together and click the button for the User lock batch job, the mixin would separate the users and locked users get unlocked while normal users get locked.

POST jobs have been added through these issues:

https://github.com/turian/audio-discrimination-crowdsource/issues/108
https://github.com/turian/audio-discrimination-crowdsource/issues/105
and AdminDeleteView which is added to the primary pr.

**Comment by turian** [comment]
Approved
