### ISSUE TITLE
Admin Batch Submit View

### ISSUE THREAD

**Issue by DeFidelity** [turian/audio-discrimination-crowdsource#92]
Depends on: https://github.com/turian/audio-discrimination-crowdsource/blob/main/README-spec.md#admin-batch-submit-view

@turian please don't forget to spec this.

**Comment by turian** [comment]
For a particular experiment, you can upload a JSON file, or paste JSON into a text box, to add a batch.

The JSON is a dict with optional keys is_gold: boolean, and notes: text, and required key tasks.
Tasks is a list of dicts with keys: reference_url, transform_url, and optional transform_metadata as JSON.

After the JSON is submitted, the admin has the option to edit the is_gold and notes text in HTMX

**Comment by turian** [comment]
Also:

We currently have this as the DB definition for Task:

"Task: * batch: foreign key to Batch row. * reference_url: URL string. * transform_url: URL string. * transform_metadata: JSON. * experiment_type: FK to ExperimentType."

I believe we should remove experiment_type and instead have the Batch row have an FK to Experiment.

**Comment by DeFidelity** [comment]
@turian can I have an example JSON data that could be uploaded through the text field? So as to know the format it's coming with and structure my views accordingly.

**Comment by turian** [comment]
@DeFidelity It's given above

The JSON is a dict with optional keys is_gold: boolean, and notes: text, and required key tasks.
Tasks is a list of dicts with keys: reference_url, transform_url, and optional transform_metadata as JSON.

**Comment by DeFidelity** [comment]
An example JSON that could be pasted into the AdminCreateBatch experiment is:

```
{
    "is_gold": true,
    "notes": "This is a sample JSON data",
    "tasks": [
        {
            "reference_url": "https://www.example.com/reference",
            "transform_url": "https://www.example.com/transform",
            "transform_metadata": {
                "key1": "value1",
                "key2": "value2"
            }
        },
        {
            "reference_url": "https://www.example.com/reference2",
            "transform_url": "https://www.example.com/transform2"
        }
    ]
}
```
