### ISSUE TITLE
Annotators profile.

### ISSUE THREAD

**Issue by DeFidelity** [turian/audio-discrimination-crowdsource#93]
Annotators profile is introduced because of the number of attributes of annotators that are needed as spec'ed [here](https://github.com/turian/audio-discrimination-crowdsource/blob/main/README-spec.md#admin-user-view).

Model:
- name: `AnnotatorsProfile`
-  fields: 
    - email
    - number of completed tasks 
    - percent of gold correct 
        - The computation method should be attached to the model
        - no of correct gold task / total number of gold tasks assigned
    - interannotator agreement
    - ROI
        - The computation method should be attached to the model
        - tasks completed / (# hours * hourly rate)
    - delete

Profile creation would be automatic for all users that aren't admin user, this would be achieved through Django's Signal, the post save method would be used to create the profile which would be all blank save for the email field, which would be auto filled through the email user used to register himself on the site.

Other fields in the annotators profile model would be populated automatically depending on the numbers of tasks completed for each annotator and the specified hourly rate. and this logic would be added to concerned views.

**Comment by turian** [comment]
Only visible to admin.

The things not spec'ed in the database don't need to be in the database, they can be computed dynamically.

**Comment by DeFidelity** [comment]
Yes, this would only be visible to the admin, it would have no views or template but the data would be used in the admin dashboard.

**Comment by turian** [comment]
Yes. 

Most of these things do not need to be fields, they should be computed dynamically. The only things that are database fields are:

fields:
* email
* hourly rate
* locked

If they are deleted they are permanently gone and dropped from the DB. YAGNI.

What we might be missing is a way to do time-tracking. To understand how longer they worked for and thus can compute how many tasks they computed in their work time. Think about this.

**Comment by DeFidelity** [comment]
Oh, I got what you meant now, I checked the User and Task model and found that there is no way any of them is tracking the other, and there is no way to know the number of users that have worked on a task, or know which user worked on a particular task or a way to know the number of tasks a user has undertaken.
I guess we'll need to add a foreign key to the Task model to track users.

**Comment by turian** [comment]
Let's log these things:

1) When the task was shown to the user (beginning)
2) When the user submitted the task

Don't worry about time clearing. We will keep all historical time stats.

We might also want to log any time a user logs in.

**Comment by turian** [comment]
We might want to have code that if any tasks were really long, we drop them. Like the person walked away from the computer.

**Comment by DeFidelity** [comment]
If so, then expected time to complete each task needs to be added to each task then, it would be easier to have a logic read through that, for example:
if submit_time - begin_time is > task_duration, lock/drop the user.

What do you think about this?

**Comment by turian** [comment]
Nah the admin will decide. Let's figure it out later? I want to play with the admin interface before deciding
