### ISSUE TITLE
Annotators Dashboard

### ISSUE THREAD

**Issue by DeFidelity** [turian/audio-discrimination-crowdsource#94]
Literally, The annotators' landing page would be the default landing page of annotators as they log into the app.

This page would take the form of the pre-existing landing page, just with the addition of their performance reports and all.

View detail:
- name: `AnnotatorDashboard`
- render: `annotator-dashboard.html`
- context: (shows them their performance report)
     - number of tasks completed
     - percent of gold correct
     - interannotator agreement
     - Hourly rate
     - ROI

Then a button to take on a task as default (presently) would be placed on the page for annotators to continue with their job.

**Comment by turian** [comment]
Not needed. Annotators don't need to see their own profile / stats.

**Comment by DeFidelity** [comment]
It would be scraped and the issue would be closed now.
